from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView
from .views import *
urlpatterns = [
    path('', inicio, name='inicio'),
    path("registro/", registro, name="registro"),
    path('logout_message', logout_message, name='logout_message'),
    path('timeout', timeout, name='timeout'),
    path('formacion_completa', formacion_completa, name='formacion_completa'),
    path('completar_teoria', completar_teoria, name='completar_teoria'),
    path('completar_practica', completar_practica, name='completar_practica'),
    path('completar_producto', completar_producto, name='completar_producto'),
    path('formacion_opis', formacion_opis, name='formacion_opis'),
    path('actualizar_matriz', actualizar_matriz, name='actualizar_matriz'),
    path('editar_matriz', editar_matriz, name='editar_matriz'),
    path('agregar_tecnico', agregar_tecnico, name='agregar_tecnico'),
    path('eliminar_tecnico', eliminar_tecnico, name='eliminar_tecnico'),
    path('editar_tecnico', editar_tecnico, name='editar_tecnico'),
    path('nueva_opi', nueva_opi, name='nueva_opi'),
    path('guardar_opi', guardar_opi, name='guardar_opi'),
    path('listar_opis', listar_opis, name='listar_opis'),
    path('aceptar_opi/', aceptar_opi, name='aceptar_opi'),
    path('rechazar_opi/', rechazar_opi, name='rechazar_opi'), 
    path('introducir_fecha', introducir_fecha, name='introducir_fecha'),
    path('guardar_fecha', guardar_fecha, name='guardar_fecha'),
    path('introducir_firma', introducir_firma, name='introducir_firma'),
    path('firmar_formacion', firmar_formacion, name='firmar_formacion'),
    path('subir_firma', subir_firma, name='subir_firma'),
    path('guardar_firma', guardar_firma, name='guardar_firma'),
    path('generar_pdf', generar_pdf, name='generar_pdf'),
    path('ver_pdf_opi/<str:opi>/<str:nombre>/', ver_pdf_opi, name='ver_pdf_opi'),
    path('ver_pdf_form/<str:nombre>/<str:puesto>/', ver_pdf_form, name='ver_pdf_form'),
    path('descargar_polivalencia/', descargar_polivalencia, name='descargar_polivalencia'),
    path('notificaciones', notificaciones, name='notificaciones'),
    path('notificacion_leida/<int:notificacion_id>/', notificacion_leida, name='notificacion_leida'),
    path('password_change/', CambioPasswordView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('grafica', grafica, name='grafica'),
    path('auditoria_diaria', auditoria_diaria, name='auditoria_diaria'),
    path('registrar_auditoria', registrar_auditoria, name='registrar_auditoria'),
    path('edicion_plantillas', edicion_plantillas, name='edicion_plantillas'),
]
