# Generated by Django 5.2.7 on 2025-10-10 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIA', models.DateField()),
                ('SAP', models.CharField(max_length=100)),
                ('NUM_SERIE', models.CharField(max_length=100)),
                ('FAMILIA', models.CharField(max_length=100)),
                ('PROCESO', models.CharField(max_length=100)),
                ('AUDITOR', models.CharField(max_length=100)),
                ('OPERARIO', models.CharField(max_length=100)),
                ('NO_CONFORMIDAD', models.BooleanField(default=False)),
                ('OBSERVACIONES', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='completa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUESTO', models.CharField(max_length=100)),
                ('OPERARIO', models.CharField(max_length=100)),
                ('TEORIA', models.BooleanField(default=False)),
                ('PRACTICA', models.BooleanField(default=False)),
                ('PRODUCTO', models.BooleanField(default=False)),
                ('firmas', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='nuevas_opis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPI', models.CharField(max_length=100, unique=True)),
                ('INFO', models.CharField(max_length=800)),
                ('SECCION1', models.CharField(max_length=25)),
                ('SECCION2', models.CharField(max_length=25)),
                ('SECCION3', models.CharField(max_length=25)),
                ('SECCION4', models.CharField(max_length=25)),
                ('SECCION5', models.CharField(max_length=25)),
                ('SECCION6', models.CharField(max_length=25)),
                ('SECCION7', models.CharField(max_length=25)),
                ('ok_supervisor', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='opis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPI', models.CharField(max_length=100, unique=True)),
                ('INFO', models.CharField(max_length=800)),
                ('SECCION1', models.CharField(max_length=25)),
                ('SECCION2', models.CharField(max_length=25)),
                ('SECCION3', models.CharField(max_length=25)),
                ('SECCION4', models.CharField(max_length=25)),
                ('SECCION5', models.CharField(max_length=25)),
                ('SECCION6', models.CharField(max_length=25)),
                ('SECCION7', models.CharField(max_length=25)),
                ('formados', models.JSONField(default=dict)),
                ('firmas', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='polivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPERARIO', models.CharField(max_length=100, unique=True)),
                ('CONFIRM', models.IntegerField(default=0)),
                ('OPEN_MAIL', models.IntegerField(default=0)),
                ('ORDER_ENTRY_SERVICE', models.IntegerField(default=0)),
                ('ORDER_ENTRY_NEW', models.IntegerField(default=0)),
                ('DIAG_ITE', models.IntegerField(default=0)),
                ('DIAG_ITE_SAF', models.IntegerField(default=0)),
                ('DIAG_SDS', models.IntegerField(default=0)),
                ('DIAG_SDS_SAF', models.IntegerField(default=0)),
                ('DIAG_BTE', models.IntegerField(default=0)),
                ('DIAG_FM_DWA', models.IntegerField(default=0)),
                ('DIAG_TITANIUM', models.IntegerField(default=0)),
                ('REPAIR_FM_DWA', models.IntegerField(default=0)),
                ('REPAIR_CARGADORES', models.IntegerField(default=0)),
                ('REPAIR_BTE', models.IntegerField(default=0)),
                ('RSM', models.IntegerField(default=0)),
                ('MINI_KITTING', models.IntegerField(default=0)),
                ('KITTING_CUSTOM', models.IntegerField(default=0)),
                ('KITTING_BTE', models.IntegerField(default=0)),
                ('DCC', models.IntegerField(default=0)),
                ('DLP', models.IntegerField(default=0)),
                ('KIT_PREP_SDS', models.IntegerField(default=0)),
                ('CLOSING_SDS', models.IntegerField(default=0)),
                ('KIT_PREP_ITE', models.IntegerField(default=0)),
                ('CLOSING_ITE', models.IntegerField(default=0)),
                ('CUT_TRIM', models.IntegerField(default=0)),
                ('FL', models.IntegerField(default=0)),
                ('TITANIUM', models.IntegerField(default=0)),
                ('VISUAL_ITE', models.IntegerField(default=0)),
                ('VISUAL_SDS', models.IntegerField(default=0)),
                ('VISUAL_BTE', models.IntegerField(default=0)),
                ('VISUAL_FM_DWA', models.IntegerField(default=0)),
                ('PRO_GO_ITE', models.IntegerField(default=0)),
                ('PRO_GO_SDS', models.IntegerField(default=0)),
                ('PRO_GO_BTE', models.IntegerField(default=0)),
                ('PRO_GO_FM_DWA', models.IntegerField(default=0)),
                ('PACKING_NEW', models.IntegerField(default=0)),
                ('PACKING_SERVICE', models.IntegerField(default=0)),
                ('RPM_DESMONTAJE_LIMPIEZA', models.IntegerField(default=0)),
                ('RPM_DECONTAMINACION', models.IntegerField(default=0)),
                ('RPM_IRS1_IDENTIFICACION', models.IntegerField(default=0)),
                ('RPM_LPS2_BLUETOOTH', models.IntegerField(default=0)),
                ('RPM_VISUAL_SNW2', models.IntegerField(default=0)),
                ('ACS2', models.IntegerField(default=0)),
                ('SORTING', models.IntegerField(default=0)),
                ('REFURBISHING', models.IntegerField(default=0)),
                ('REPROCESSING_CARGADORES', models.IntegerField(default=0)),
                ('PACKING_RPM_REFURBISHING', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
